PRCP-1003-Customer Transaction Prediction

Problem Statement

Task 1:-Prepare a complete data analysis report on the given data.

Task 2:-Create a predictive model which will help the bank to identify which customer will make transactions in future.

In [1]:
#Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.simplefilter('ignore')
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, roc_auc_score, confusion_matrix, classification_report

In [2]:
#Reading the Datd Set .
df=pd.read_csv('train(1).csv')

In [3]:
df.head()

,ID_code,target,var_0,var_1,var_2,var_3,var_4,var_5,var_6,var_7,...,var_190,var_191,var_192,var_193,var_194,var_195,var_196,var_197,var_198,var_199
0,train_0,0,8.9255,-6.7863,11.9081,5.0930,11.4607,-9.2834,5.1187,18.6266,...,4.4354,3.9642,3.1364,1.6910,18.5227,-2.3978,7.8784,8.5635,12.7803,-1.0914
1,train_1,0,11.5006,-4.1473,13.8588,5.3890,12.3622,7.0433,5.6208,16.5338,...,7.6421,7.7214,2.5837,10.9516,15.4305,2.0339,8.1267,8.7889,18.3560,1.9518
2,train_2,0,8.6093,-2.7457,12.0805,7.8928,10.5825,-9.0837,6.9427,14.6155,...,2.9057,9.7905,1.6704,1.6858,21.6042,3.1417,-6.5213,8.2675,14.7222,0.3965
3,train_3,0,11.0604,-2.1518,8.9522,7.1957,12.5846,-1.8361,5.8428,14.9250,...,4.4666,4.7433,0.7178,1.4214,23.0347,-1.2706,-2.9275,10.2922,17.9697,-8.9996
4,train_4,0,9.8369,-1.4834,12.8746,6.6375,12.2772,2.4486,5.9405,19.2514,...,-1.4905,9.5214,-0.1508,9.1942,13.2876,-1.5121,3.9267,9.5031,17.9974,-8.8104

In [4]:
df.shape

(200000, 202)

In [5]:
df['target'].value_counts()

target
0    179902
1     20098
Name: count, dtype: int64

In [6]:
#Checking the null value 
df.isnull().sum()

ID_code    0
target     0
var_0      0
var_1      0
var_2      0
          ..
var_195    0
var_196    0
var_197    0
var_198    0
var_199    0
Length: 202, dtype: int64

In [7]:
df.describe()

,target,var_0,var_1,var_2,var_3,var_4,var_5,var_6,var_7,var_8,...,var_190,var_191,var_192,var_193,var_194,var_195,var_196,var_197,var_198,var_199
count,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,...,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000
mean,0.100490,10.679914,-1.627622,10.715192,6.796529,11.078333,-5.065317,5.408949,16.545850,0.284162,...,3.234440,7.438408,1.927839,3.331774,17.993784,-0.142088,2.303335,8.908158,15.870720,-3.326537
std,0.300653,3.040051,4.050044,2.640894,2.043319,1.623150,7.863267,0.866607,3.418076,3.332634,...,4.559922,3.023272,1.478423,3.992030,3.135162,1.429372,5.454369,0.921625,3.010945,10.438015
min,0.000000,0.408400,-15.043400,2.117100,-0.040200,5.074800,-32.562600,2.347300,5.349700,-10.505500,...,-14.093300,-2.691700,-3.814500,-11.783400,8.694400,-5.261000,-14.209600,5.960600,6.299300,-38.852800
25%,0.000000,8.453850,-4.740025,8.722475,5.254075,9.883175,-11.200350,4.767700,13.943800,-2.317800,...,-0.058825,5.157400,0.889775,0.584600,15.629800,-1.170700,-1.946925,8.252800,13.829700,-11.208475
50%,0.000000,10.524750,-1.608050,10.580000,6.825000,11.108250,-4.833150,5.385100,16.456800,0.393700,...,3.203600,7.347750,1.901300,3.396350,17.957950,-0.172700,2.408900,8.888200,15.934050,-2.819550
75%,0.000000,12.758200,1.358625,12.516700,8.324100,12.261125,0.924800,6.003000,19.102900,2.937900,...,6.406200,9.512525,2.949500,6.205800,20.396525,0.829600,6.556725,9.593300,18.064725,4.836800
max,1.000000,20.315000,10.376800,19.353000,13.188300,16.671400,17.251600,8.447700,27.691800,10.151300,...,18.440900,16.716500,8.402400,18.281800,27.928800,4.272900,18.321500,12.000400,26.079100,28.500700

In [8]:
df.head(0)

Empty DataFrame
Columns: [ID_code, target, var_0, var_1, var_2, var_3, var_4, var_5, var_6, var_7, var_8, var_9, var_10, var_11, var_12, var_13, var_14, var_15, var_16, var_17, var_18, var_19, var_20, var_21, var_22, var_23, var_24, var_25, var_26, var_27, var_28, var_29, var_30, var_31, var_32, var_33, var_34, var_35, var_36, var_37, var_38, var_39, var_40, var_41, var_42, var_43, var_44, var_45, var_46, var_47, var_48, var_49, var_50, var_51, var_52, var_53, var_54, var_55, var_56, var_57, var_58, var_59, var_60, var_61, var_62, var_63, var_64, var_65, var_66, var_67, var_68, var_69, var_70, var_71, var_72, var_73, var_74, var_75, var_76, var_77, var_78, var_79, var_80, var_81, var_82, var_83, var_84, var_85, var_86, var_87, var_88, var_89, var_90, var_91, var_92, var_93, var_94, var_95, var_96, var_97, ...]
Index: []

[0 rows x 202 columns]

In [9]:
X=df.drop(['ID_code','target'],axis=1)
y=df['target']

In [10]:
df.target.value_counts()

target
0    179902
1     20098
Name: count, dtype: int64

In [11]:
# Balancing the data 
df_maj=df[df.target==0]
df_min=df[df.target==1]

In [12]:
from sklearn.utils import resample

In [13]:
df_min_upsampled= resample(df_min,replace=True,n_samples=179902,random_state=123)
df_upsampled=pd.concat([df_maj,df_min_upsampled])
df_upsampled.target.value_counts()

target
0    179902
1    179902
Name: count, dtype: int64

 Now data got balanced .

In [14]:
X=df_upsampled.iloc[:,2:]
y=df_upsampled.iloc[:,1:2]

# Model creation and checking Accuracy

In [15]:
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size=0.2,random_state=42)

In [16]:
Model1 =  LogisticRegression()
Model1.fit(X_train,y_train)

LogisticRegression()

In [17]:
pred1=Model1.predict(X_test)

In [18]:
accuracy_score(y_test,pred1)

0.7703061380469977

In [19]:
Model2= RandomForestClassifier(n_estimators=50,max_depth=8,n_jobs=-1,random_state=42)

In [20]:
Model2.fit(X_train,y_train)

RandomForestClassifier(max_depth=8, n_estimators=50, n_jobs=-1, random_state=42)

In [21]:
pred2=Model2.predict(X_test)

In [22]:
accuracy_score(y_test,pred2)

0.7499200956073429

In [24]:
import lightgbm as lgb

In [25]:
Model3= lgb.LGBMClassifier(n_estimators=300,max_depth=8,n_jobs=-1,random_state=42)

In [26]:
Model3.fit(X_train,y_train)

[LightGBM] [Info] Number of positive: 144021, number of negative: 143822
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.663171 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 51000
[LightGBM] [Info] Number of data points in the train set: 287843, number of used features: 200
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.500346 -> initscore=0.001383
[LightGBM] [Info] Start training from score 0.001383

LGBMClassifier(max_depth=8, n_estimators=300, n_jobs=-1, random_state=42)

In [27]:
pred3=Model3.predict(X_test)

In [28]:
accuracy_score(y_test,pred3)

0.8860632842789844

In [33]:
print("Accuracy:", accuracy_score(y_test, pred3))
print("ROC-AUC:", roc_auc_score(y_test, pred3))
print("\nClassification Report:\n", classification_report(y_test, pred3))
print("\nClassification Report:\n", classification_report(y_test, pred3))

Accuracy: 0.8860632842789844
ROC-AUC: 0.886105492156847

Classification Report:
               precision    recall  f1-score   support

           0       0.90      0.87      0.88     36080
           1       0.87      0.90      0.89     35881

    accuracy                           0.89     71961
   macro avg       0.89      0.89      0.89     71961
weighted avg       0.89      0.89      0.89     71961


Classification Report:
               precision    recall  f1-score   support

           0       0.90      0.87      0.88     36080
           1       0.87      0.90      0.89     35881

    accuracy                           0.89     71961
   macro avg       0.89      0.89      0.89     71961
weighted avg       0.89      0.89      0.89     71961

In this project, multiple machine learning models were developed to predict which customers will make future transactions using the anonymized PRCP-1003 dataset. After testing Logistic Regression, Random Forest, XGBoost, and LightGBM models, LightGBM achieved the highest accuracy and best overall performance. It is therefore recommended as the final model for production use to help the bank identify and target potential customers more effectively.

After training and comparing multiple models — Logistic Regression, Random Forest, XGBoost, and LightGBM —
the LightGBM Classifier achieved the best accuracy and performance on the test data.

Hence, LightGBM is the final recommended predictive model to help the bank identify which customers are most likely to make transactions in the future.
This model offers:

High prediction accuracy

Fast training and inference speed

Strong performance on large, high-dimensional data